# Generated by Django 5.1.6 on 2025-03-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
