# Generated by Django 5.1.6 on 2025-03-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_dietaryfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=255, unique=True)),
                ('substitutes', models.JSONField(default=list)),
            ],
        ),
    ]
